# This is a basic workflow to help you get started with Actions

name: IPTV m3u encryption

# Controls when the workflow will run
on:
  # Triggers the workflow on schedule
  schedule:
    - cron: '0 3 */2 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "iptvenc"
  iptvenc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a script file using the runners shell
      - name: Run the script file
        env:
          original_file: ${{ vars.ORIGINAL_FILE }}
          smallest_file_size: ${{ vars.SMALLEST_FILE_SIZE }}
          test_channel: ${{ vars.TEST_CHANNEL }}
          temp_file: ${{ vars.TEMP_FILE }}
          target_file: ${{ vars.TARGET_FILE }}
          original_file_url: ${{ secrets.ORIGINAL_FILE_URL }}
          ua: ${{ secrets.UA }}
          password: ${{ secrets.PASSWORD }}
          algorithm: ${{ secrets.ALGORITHM }}
          ivHex: ${{ secrets.IVHEX }}
          saltHex: ${{ secrets.SALTHEX }}
          iterations: ${{ secrets.ITERATIONS }}
          diggest: ${{ secrets.DIGGEST }}
        run: bash ./scripts/renew_iptv.sh

      - name: Commit and push generated file
        run: |
          # 1. Configure the built-in GitHub Actions bot user
          git config --local user.email "github-actions[bot]@://github.com"
          git config --local user.name "github-actions[bot]"
          
          # 2. Stage the specific file (replace with your file's name)
          git add ${{ vars.TARGET_FILE }}
          
          # 3. Commit only if there are changes to avoid workflow errors
          if ! git diff --cached --quiet; then
            git commit -m "chore: automated file update [skip ci]"
            git push
          else
            echo "::notice::No changes detected. Skipping commit."
          fi

